

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50



 

  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
    gains:
      base_link__link_01: {p: 1000, d: 1, i: 1, i_clamp: 1}
      link_01__link_02: {p: 1000, d: 1, i: 1, i_clamp: 1}
      link_02__link_03: {p: 1000, d: 1, i: 1, i_clamp: 1}
     
