controller_list:
  - name: robotarm/arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    default: true
    joints: [base_link__link_01, link_01__link_02, link_02__link_03]
