# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
  gains:
    base_link__link_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_01__link_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_02__link_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1